/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package countwords;

/**
 *
 * @author herrerach_sd2082
 */
public class Htmlclass {
    String text ;

    public Htmlclass() {
        this.text = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML+RDFa 1.0//EN\" \"http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd\">\n"
                + "\n"
                + "<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->\n"
                + "<!--[if lt IE 7]> <html class=\"no-js ie6 ie\" xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" version=\"XHTML+RDFa 1.0\" dir=\"ltr\" \n"
                + "  xmlns:content=\"http://purl.org/rss/1.0/modules/content/\"\n"
                + "  xmlns:dc=\"http://purl.org/dc/terms/\"\n"
                + "  xmlns:foaf=\"http://xmlns.com/foaf/0.1/\"\n"
                + "  xmlns:og=\"http://ogp.me/ns#\"\n"
                + "  xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "  xmlns:sioc=\"http://rdfs.org/sioc/ns#\"\n"
                + "  xmlns:sioct=\"http://rdfs.org/sioc/types#\"\n"
                + "  xmlns:skos=\"http://www.w3.org/2004/02/skos/core#\"\n"
                + "  xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
                + "  xmlns:fb=\"http://ogp.me/ns/fb#\"\n"
                + "  xmlns:article=\"http://ogp.me/ns/article#\"\n"
                + "  xmlns:book=\"http://ogp.me/ns/book#\"\n"
                + "  xmlns:profile=\"http://ogp.me/ns/profile#\"\n"
                + "  xmlns:video=\"http://ogp.me/ns/video#\"> <![endif]-->\n"
                + "<!--[if IE 7]>    <html class=\"no-js ie7 ie\" xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" version=\"XHTML+RDFa 1.0\" dir=\"ltr\" \n"
                + "  xmlns:content=\"http://purl.org/rss/1.0/modules/content/\"\n"
                + "  xmlns:dc=\"http://purl.org/dc/terms/\"\n"
                + "  xmlns:foaf=\"http://xmlns.com/foaf/0.1/\"\n"
                + "  xmlns:og=\"http://ogp.me/ns#\"\n"
                + "  xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "  xmlns:sioc=\"http://rdfs.org/sioc/ns#\"\n"
                + "  xmlns:sioct=\"http://rdfs.org/sioc/types#\"\n"
                + "  xmlns:skos=\"http://www.w3.org/2004/02/skos/core#\"\n"
                + "  xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
                + "  xmlns:fb=\"http://ogp.me/ns/fb#\"\n"
                + "  xmlns:article=\"http://ogp.me/ns/article#\"\n"
                + "  xmlns:book=\"http://ogp.me/ns/book#\"\n"
                + "  xmlns:profile=\"http://ogp.me/ns/profile#\"\n"
                + "  xmlns:video=\"http://ogp.me/ns/video#\"> <![endif]-->\n"
                + "<!--[if IE 8]>    <html class=\"no-js ie8 ie\" xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" version=\"XHTML+RDFa 1.0\" dir=\"ltr\" \n"
                + "  xmlns:content=\"http://purl.org/rss/1.0/modules/content/\"\n"
                + "  xmlns:dc=\"http://purl.org/dc/terms/\"\n"
                + "  xmlns:foaf=\"http://xmlns.com/foaf/0.1/\"\n"
                + "  xmlns:og=\"http://ogp.me/ns#\"\n"
                + "  xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "  xmlns:sioc=\"http://rdfs.org/sioc/ns#\"\n"
                + "  xmlns:sioct=\"http://rdfs.org/sioc/types#\"\n"
                + "  xmlns:skos=\"http://www.w3.org/2004/02/skos/core#\"\n"
                + "  xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
                + "  xmlns:fb=\"http://ogp.me/ns/fb#\"\n"
                + "  xmlns:article=\"http://ogp.me/ns/article#\"\n"
                + "  xmlns:book=\"http://ogp.me/ns/book#\"\n"
                + "  xmlns:profile=\"http://ogp.me/ns/profile#\"\n"
                + "  xmlns:video=\"http://ogp.me/ns/video#\"> <![endif]-->\n"
                + "<!--[if IE 9]>    <html class=\"no-js ie9 ie\" xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" version=\"XHTML+RDFa 1.0\" dir=\"ltr\" \n"
                + "  xmlns:content=\"http://purl.org/rss/1.0/modules/content/\"\n"
                + "  xmlns:dc=\"http://purl.org/dc/terms/\"\n"
                + "  xmlns:foaf=\"http://xmlns.com/foaf/0.1/\"\n"
                + "  xmlns:og=\"http://ogp.me/ns#\"\n"
                + "  xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "  xmlns:sioc=\"http://rdfs.org/sioc/ns#\"\n"
                + "  xmlns:sioct=\"http://rdfs.org/sioc/types#\"\n"
                + "  xmlns:skos=\"http://www.w3.org/2004/02/skos/core#\"\n"
                + "  xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
                + "  xmlns:fb=\"http://ogp.me/ns/fb#\"\n"
                + "  xmlns:article=\"http://ogp.me/ns/article#\"\n"
                + "  xmlns:book=\"http://ogp.me/ns/book#\"\n"
                + "  xmlns:profile=\"http://ogp.me/ns/profile#\"\n"
                + "  xmlns:video=\"http://ogp.me/ns/video#\"> <![endif]-->\n"
                + "<!--[if gt IE 9]><!--> <html class=\"no-js\" xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" version=\"XHTML+RDFa 1.0\" dir=\"ltr\" \n"
                + "  xmlns:content=\"http://purl.org/rss/1.0/modules/content/\"\n"
                + "  xmlns:dc=\"http://purl.org/dc/terms/\"\n"
                + "  xmlns:foaf=\"http://xmlns.com/foaf/0.1/\"\n"
                + "  xmlns:og=\"http://ogp.me/ns#\"\n"
                + "  xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "  xmlns:sioc=\"http://rdfs.org/sioc/ns#\"\n"
                + "  xmlns:sioct=\"http://rdfs.org/sioc/types#\"\n"
                + "  xmlns:skos=\"http://www.w3.org/2004/02/skos/core#\"\n"
                + "  xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
                + "  xmlns:fb=\"http://ogp.me/ns/fb#\"\n"
                + "  xmlns:article=\"http://ogp.me/ns/article#\"\n"
                + "  xmlns:book=\"http://ogp.me/ns/book#\"\n"
                + "  xmlns:profile=\"http://ogp.me/ns/profile#\"\n"
                + "  xmlns:video=\"http://ogp.me/ns/video#\"> <!--<![endif]-->\n"
                + "\n"
                + "<head profile=\"http://www.w3.org/1999/xhtml/vocab\">\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n"
                + "<link rel=\"shortcut icon\" href=\"https://ateneo.edu/sites/default/files/logo_1.png\" type=\"image/png\" />\n"
                + "<meta name=\"description\" content=\"We will dare you to discover a larger vision of yourself and our world. We will challenge you to do &quot;the things of greater worth&quot; because we know you are more than what the grade-givers of this world make you out to be. We do this because the Ateneo is more than just a school. WELCOME\" />\n"
                + "<meta name=\"generator\" content=\"Drupal 7 (http://drupal.org)\" />\n"
                + "<link rel=\"canonical\" href=\"https://ateneo.edu/admissions\" />\n"
                + "<link rel=\"shortlink\" href=\"https://ateneo.edu/node/4797\" />\n"
                + "<meta property=\"og:site_name\" content=\"Ateneo de Manila University\" />\n"
                + "<meta property=\"og:type\" content=\"article\" />\n"
                + "<meta property=\"og:url\" content=\"https://ateneo.edu/admissions\" />\n"
                + "<meta property=\"og:title\" content=\"Admissions\" />\n"
                + "<meta property=\"og:description\" content=\"We will dare you to discover a larger vision of yourself and our world. We will challenge you to do &quot;the things of greater worth&quot; because we know you are more than what the grade-givers of this world make you out to be. We do this because the Ateneo is more than just a school. WELCOME\" />\n"
                + "<meta property=\"og:updated_time\" content=\"2018-01-04T09:13:44+08:00\" />\n"
                + "<meta property=\"article:published_time\" content=\"2013-05-07T10:22:23+08:00\" />\n"
                + "<meta property=\"article:modified_time\" content=\"2018-01-04T09:13:44+08:00\" />\n"
                + "    <title>Admissions | Ateneo de Manila University</title>\n"
                + "  <style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/modules/system/system.base.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/modules/system/system.menus.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/modules/system/system.messages.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/modules/system/system.theme.css?pxanmc\");\n"
                + "</style>\n"
                + "<style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/misc/ui/jquery.ui.core.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/misc/ui/jquery.ui.theme.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/misc/ui/jquery.ui.button.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/misc/ui/jquery.ui.resizable.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/misc/ui/jquery.ui.dialog.css?pxanmc\");\n"
                + "</style>\n"
                + "<style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/calendar/css/calendar_multiday.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/modules/comment/comment.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/date/date_api/date.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/date/date_popup/themes/datepicker.1.7.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/modules/field/theme/field.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/modules/node/node.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/modules/search/search.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/modules/user/user.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/views/css/views.css?pxanmc\");\n"
                + "</style>\n"
                + "<style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/ckeditor/ckeditor.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/colorbox/styles/stockholmsyndrome/colorbox_stockholmsyndrome.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/ctools/css/ctools.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/simple_dialog/css/simple_dialog.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/libraries/superfish/css/superfish.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/libraries/superfish/css/superfish-vertical.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/libraries/superfish/css/superfish-navbar.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/twitter_profile_widget/twitter_profile_widget.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/video/css/video.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/views_slideshow/views_slideshow.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/responsive_menus/styles/responsive_menus_simple/css/responsive_menus_simple.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/custom_search/custom_search.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/views_slideshow/views_slideshow_controls_text.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/views_slideshow/contrib/views_slideshow_cycle/views_slideshow_cycle.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/modules/path_breadcrumbs/path_breadcrumbs.css?pxanmc\");\n"
                + "</style>\n"
                + "\n"
                + "<!--[if lt IE 10]>\n"
                + "<style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/ctools/css/d41d8cd98f00b204e9800998ecf8427e.css?pxanmc\");\n"
                + "</style>\n"
                + "<![endif]-->\n"
                + "<style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/sites/all/themes/fusion/fusion_core/css/fusion-style.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/themes/fusion/fusion_core/css/fusion-typography.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/themes/fusion/fusion_core/skins/core/fusion-core-skins.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/themes/fusion/ateneo/css/ateneo.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/themes/fusion/ateneo/css/lor-main.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/themes/fusion/ateneo/css/ateneo-blocks.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/themes/fusion/ateneo/css/fusion-starter-style.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/all/themes/fusion/ateneo/css/bgstretcher.css?pxanmc\");\n"
                + "</style>\n"
                + "<style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/sites/all/themes/fusion/fusion_core/css/grid12-960.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_6.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_11.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_14.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_18.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_21.css?pxanmc\");\n"
                + "</style>\n"
                + "<link type=\"text/css\" rel=\"stylesheet\" href=\"https://ateneo.edu/sites/default/files/css_injector/css_injector_22.css?pxanmc\" media=\"all\" />\n"
                + "<style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_37.css?pxanmc\");\n"
                + "</style>\n"
                + "<link type=\"text/css\" rel=\"stylesheet\" href=\"https://ateneo.edu/sites/default/files/css_injector/css_injector_40.css?pxanmc\" media=\"all\" />\n"
                + "<style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_41.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_43.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_44.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_46.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_49.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_51.css?pxanmc\");\n"
                + "</style>\n"
                + "<link type=\"text/css\" rel=\"stylesheet\" href=\"https://ateneo.edu/sites/default/files/css_injector/css_injector_62.css?pxanmc\" media=\"all\" />\n"
                + "<style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_67.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_70.css?pxanmc\");\n"
                + "</style>\n"
                + "<link type=\"text/css\" rel=\"stylesheet\" href=\"https://ateneo.edu/sites/default/files/css_injector/css_injector_79.css?pxanmc\" media=\"all\" />\n"
                + "<style type=\"text/css\" media=\"all\">\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_100.css?pxanmc\");\n"
                + "@import url(\"https://ateneo.edu/sites/default/files/css_injector/css_injector_105.css?pxanmc\");\n"
                + "</style>\n"
                + "    \n"
                + "  \n"
                + "	    \n"
                + "        \n"
                + "  <script type=\"text/javascript\" src=\"//ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js\"></script>\n"
                + "<script type=\"text/javascript\">\n"
                + "<!--//--><![CDATA[//><!--\n"
                + "window.jQuery || document.write(\"<script src='/sites/all/modules/jquery_update/replace/jquery/1.5/jquery.min.js'>\\x3C/script>\")\n"
                + "//--><!]]>\n"
                + "</script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/jquery.once.js?v=1.2\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/drupal.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/ui/jquery.ui.core.min.js?v=1.8.7\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/ui/jquery.ui.widget.min.js?v=1.8.7\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/ui/jquery.ui.button.min.js?v=1.8.7\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/ui/jquery.ui.mouse.min.js?v=1.8.7\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/ui/jquery.ui.draggable.min.js?v=1.8.7\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/ui/jquery.ui.position.min.js?v=1.8.7\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/ui/jquery.ui.resizable.min.js?v=1.8.7\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/ui/jquery.ui.dialog.min.js?v=1.8.7\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/views/js/jquery.ui.dialog.patch.js?v=1.8.7\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/jquery_update/replace/ui/external/jquery.cookie.js?v=67fb34f6a866c40d0570\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/jquery_update/replace/misc/jquery.form.min.js?v=2.69\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/form.js?v=7.59\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/ajax.js?v=7.59\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/jquery_update/js/jquery_update.js?v=0.0.1\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/jquery/jquery-1.11.0.min.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/jqmulti/js/switch.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/colorbox/colorbox/jquery.colorbox-min.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/colorbox/js/colorbox.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/colorbox/styles/stockholmsyndrome/colorbox_stockholmsyndrome.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/colorbox/js/colorbox_load.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/colorbox/js/colorbox_inline.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/cufon/cufon-yui.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/cufon/js/cufon-drupal.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/simple_dialog/js/simple_dialog.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/superfish/jquery.hoverIntent.minified.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/superfish/jquery.bgiframe.min.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/superfish/superfish.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/superfish/supersubs.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/superfish/supposition.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/superfish/sftouchscreen.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"http://widgets.twimg.com/j/2/widget.js\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/video/js/video.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/views_slideshow/js/views_slideshow.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/custom_search/js/custom_search.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/views/js/base.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/misc/progress.js?v=7.59\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/responsive_menus/styles/responsive_menus_simple/js/responsive_menus_simple.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/google_analytics/googleanalytics.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\">\n"
                + "<!--//--><![CDATA[//><!--\n"
                + "var _gaq = _gaq || [];_gaq.push([\"_setAccount\", \"UA-36497776-1\"]);_gaq.push([\"_trackPageview\"]);(function() {var ga = document.createElement(\"script\");ga.type = \"text/javascript\";ga.async = true;ga.src = (\"https:\" == document.location.protocol ? \"https://ssl\" : \"http://www\") + \".google-analytics.com/ga.js\";var s = document.getElementsByTagName(\"script\")[0];s.parentNode.insertBefore(ga, s);})();\n"
                + "//--><!]]>\n"
                + "</script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/views/js/ajax_view.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/views_load_more/views_load_more.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/modules/views_slideshow/contrib/views_slideshow_cycle/js/views_slideshow_cycle.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/jquery.cycle/jquery.cycle.all.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/libraries/json2/json2.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\">\n"
                + "<!--//--><![CDATA[//><!--\n"
                + "jQuery(function(){\n"
                + "jQuery('#superfish-18').supersubs({minWidth: 12, maxWidth: 27, extraWidth: 1}).superfish({\n"
                + "animation: {opacity:'show',height:'show'},\n"
                + "speed: 'fast',\n"
                + "autoArrows: false,\n"
                + "dropShadows: true});\n"
                + "});\n"
                + "//--><!]]>\n"
                + "</script>\n"
                + "<script type=\"text/javascript\">\n"
                + "<!--//--><![CDATA[//><!--\n"
                + "jQuery(function(){\n"
                + "jQuery('#superfish-5').supersubs({minWidth: 12, maxWidth: 27, extraWidth: 1}).superfish({\n"
                + "animation: {opacity:'show'},\n"
                + "speed: 'fast',\n"
                + "autoArrows: false,\n"
                + "dropShadows: true});\n"
                + "});\n"
                + "//--><!]]>\n"
                + "</script>\n"
                + "<script type=\"text/javascript\">\n"
                + "<!--//--><![CDATA[//><!--\n"
                + "jQuery(function(){\n"
                + "jQuery('#superfish-18').supersubs({minWidth: 12, maxWidth: 27, extraWidth: 1}).superfish({\n"
                + "animation: {opacity:'show',height:'show'},\n"
                + "speed: 'fast',\n"
                + "autoArrows: false,\n"
                + "dropShadows: true});\n"
                + "});\n"
                + "//--><!]]>\n"
                + "</script>\n"
                + "<script type=\"text/javascript\">\n"
                + "<!--//--><![CDATA[//><!--\n"
                + "jQuery(function(){\n"
                + "jQuery('#superfish-5').supersubs({minWidth: 12, maxWidth: 27, extraWidth: 1}).superfish({\n"
                + "animation: {opacity:'show'},\n"
                + "speed: 'fast',\n"
                + "autoArrows: false,\n"
                + "dropShadows: true});\n"
                + "});\n"
                + "//--><!]]>\n"
                + "</script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/themes/fusion/fusion_core/js/script.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/themes/fusion/ateneo/js/jquery.backstretch.min.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/themes/fusion/ateneo/js/bgstretcher.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/all/themes/fusion/ateneo/js/scripts.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/default/files/js_injector/js_injector_3.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/default/files/js_injector/js_injector_14.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/default/files/js_injector/js_injector_17.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/default/files/js_injector/js_injector_36.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\" src=\"https://ateneo.edu/sites/default/files/js_injector/js_injector_43.js?pxanmc\"></script>\n"
                + "<script type=\"text/javascript\">\n"
                + "<!--//--><![CDATA[//><!--\n"
                + "jQuery.extend(Drupal.settings, {\"basePath\":\"\\/\",\"pathPrefix\":\"\",\"ajaxPageState\":{\"theme\":\"ateneo\",\"theme_token\":\"6xS2xlhRhpS2t1Y2M7oGlEwl0LYCCDMJfF_SgK6aV1w\",\"jquery_version\":\"1.5\",\"js\":{\"0\":1,\"\\/\\/ajax.googleapis.com\\/ajax\\/libs\\/jquery\\/1.5.2\\/jquery.min.js\":1,\"1\":1,\"misc\\/jquery.once.js\":1,\"misc\\/drupal.js\":1,\"misc\\/ui\\/jquery.ui.core.min.js\":1,\"misc\\/ui\\/jquery.ui.widget.min.js\":1,\"misc\\/ui\\/jquery.ui.button.min.js\":1,\"misc\\/ui\\/jquery.ui.mouse.min.js\":1,\"misc\\/ui\\/jquery.ui.draggable.min.js\":1,\"misc\\/ui\\/jquery.ui.position.min.js\":1,\"misc\\/ui\\/jquery.ui.resizable.min.js\":1,\"misc\\/ui\\/jquery.ui.dialog.min.js\":1,\"sites\\/all\\/modules\\/views\\/js\\/jquery.ui.dialog.patch.js\":1,\"sites\\/all\\/modules\\/jquery_update\\/replace\\/ui\\/external\\/jquery.cookie.js\":1,\"sites\\/all\\/modules\\/jquery_update\\/replace\\/misc\\/jquery.form.min.js\":1,\"misc\\/form.js\":1,\"misc\\/ajax.js\":1,\"sites\\/all\\/modules\\/jquery_update\\/js\\/jquery_update.js\":1,\"sites\\/all\\/libraries\\/jquery\\/jquery-1.11.0.min.js\":1,\"sites\\/all\\/modules\\/jqmulti\\/js\\/switch.js\":1,\"sites\\/all\\/libraries\\/colorbox\\/colorbox\\/jquery.colorbox-min.js\":1,\"sites\\/all\\/modules\\/colorbox\\/js\\/colorbox.js\":1,\"sites\\/all\\/modules\\/colorbox\\/styles\\/stockholmsyndrome\\/colorbox_stockholmsyndrome.js\":1,\"sites\\/all\\/modules\\/colorbox\\/js\\/colorbox_load.js\":1,\"sites\\/all\\/modules\\/colorbox\\/js\\/colorbox_inline.js\":1,\"sites\\/all\\/libraries\\/cufon\\/cufon-yui.js\":1,\"sites\\/all\\/modules\\/cufon\\/js\\/cufon-drupal.js\":1,\"sites\\/all\\/modules\\/simple_dialog\\/js\\/simple_dialog.js\":1,\"sites\\/all\\/libraries\\/superfish\\/jquery.hoverIntent.minified.js\":1,\"sites\\/all\\/libraries\\/superfish\\/jquery.bgiframe.min.js\":1,\"sites\\/all\\/libraries\\/superfish\\/superfish.js\":1,\"sites\\/all\\/libraries\\/superfish\\/supersubs.js\":1,\"sites\\/all\\/libraries\\/superfish\\/supposition.js\":1,\"sites\\/all\\/libraries\\/superfish\\/sftouchscreen.js\":1,\"http:\\/\\/widgets.twimg.com\\/j\\/2\\/widget.js\":1,\"sites\\/all\\/modules\\/video\\/js\\/video.js\":1,\"sites\\/all\\/modules\\/views_slideshow\\/js\\/views_slideshow.js\":1,\"sites\\/all\\/modules\\/custom_search\\/js\\/custom_search.js\":1,\"sites\\/all\\/modules\\/views\\/js\\/base.js\":1,\"misc\\/progress.js\":1,\"sites\\/all\\/modules\\/responsive_menus\\/styles\\/responsive_menus_simple\\/js\\/responsive_menus_simple.js\":1,\"sites\\/all\\/modules\\/google_analytics\\/googleanalytics.js\":1,\"2\":1,\"sites\\/all\\/modules\\/views\\/js\\/ajax_view.js\":1,\"sites\\/all\\/modules\\/views_load_more\\/views_load_more.js\":1,\"sites\\/all\\/modules\\/views_slideshow\\/contrib\\/views_slideshow_cycle\\/js\\/views_slideshow_cycle.js\":1,\"sites\\/all\\/libraries\\/jquery.cycle\\/jquery.cycle.all.js\":1,\"sites\\/all\\/libraries\\/json2\\/json2.js\":1,\"3\":1,\"4\":1,\"5\":1,\"6\":1,\"sites\\/all\\/themes\\/fusion\\/fusion_core\\/js\\/script.js\":1,\"sites\\/all\\/themes\\/fusion\\/ateneo\\/js\\/jquery.backstretch.min.js\":1,\"sites\\/all\\/themes\\/fusion\\/ateneo\\/js\\/bgstretcher.js\":1,\"sites\\/all\\/themes\\/fusion\\/ateneo\\/js\\/scripts.js\":1,\"sites\\/default\\/files\\/js_injector\\/js_injector_3.js\":1,\"sites\\/default\\/files\\/js_injector\\/js_injector_14.js\":1,\"sites\\/default\\/files\\/js_injector\\/js_injector_17.js\":1,\"sites\\/default\\/files\\/js_injector\\/js_injector_36.js\":1,\"sites\\/default\\/files\\/js_injector\\/js_injector_43.js\":1},\"css\":{\"modules\\/system\\/system.base.css\":1,\"modules\\/system\\/system.menus.css\":1,\"modules\\/system\\/system.messages.css\":1,\"modules\\/system\\/system.theme.css\":1,\"misc\\/ui\\/jquery.ui.core.css\":1,\"misc\\/ui\\/jquery.ui.theme.css\":1,\"misc\\/ui\\/jquery.ui.button.css\":1,\"misc\\/ui\\/jquery.ui.resizable.css\":1,\"misc\\/ui\\/jquery.ui.dialog.css\":1,\"sites\\/all\\/modules\\/calendar\\/css\\/calendar_multiday.css\":1,\"modules\\/comment\\/comment.css\":1,\"sites\\/all\\/modules\\/date\\/date_api\\/date.css\":1,\"sites\\/all\\/modules\\/date\\/date_popup\\/themes\\/datepicker.1.7.css\":1,\"modules\\/field\\/theme\\/field.css\":1,\"modules\\/node\\/node.css\":1,\"modules\\/search\\/search.css\":1,\"modules\\/user\\/user.css\":1,\"sites\\/all\\/modules\\/views\\/css\\/views.css\":1,\"sites\\/all\\/modules\\/ckeditor\\/ckeditor.css\":1,\"sites\\/all\\/modules\\/colorbox\\/styles\\/stockholmsyndrome\\/colorbox_stockholmsyndrome.css\":1,\"sites\\/all\\/modules\\/ctools\\/css\\/ctools.css\":1,\"sites\\/all\\/modules\\/simple_dialog\\/css\\/simple_dialog.css\":1,\"sites\\/all\\/libraries\\/superfish\\/css\\/superfish.css\":1,\"sites\\/all\\/libraries\\/superfish\\/css\\/superfish-vertical.css\":1,\"sites\\/all\\/libraries\\/superfish\\/css\\/superfish-navbar.css\":1,\"sites\\/all\\/modules\\/twitter_profile_widget\\/twitter_profile_widget.css\":1,\"sites\\/all\\/modules\\/video\\/css\\/video.css\":1,\"sites\\/all\\/modules\\/views_slideshow\\/views_slideshow.css\":1,\"sites\\/all\\/modules\\/responsive_menus\\/styles\\/responsive_menus_simple\\/css\\/responsive_menus_simple.css\":1,\"sites\\/all\\/modules\\/custom_search\\/custom_search.css\":1,\"sites\\/all\\/modules\\/views_slideshow\\/views_slideshow_controls_text.css\":1,\"sites\\/all\\/modules\\/views_slideshow\\/contrib\\/views_slideshow_cycle\\/views_slideshow_cycle.css\":1,\"sites\\/all\\/modules\\/path_breadcrumbs\\/path_breadcrumbs.css\":1,\"public:\\/\\/ctools\\/css\\/d41d8cd98f00b204e9800998ecf8427e.css\":1,\"sites\\/all\\/themes\\/fusion\\/fusion_core\\/css\\/fusion-style.css\":1,\"sites\\/all\\/themes\\/fusion\\/fusion_core\\/css\\/fusion-typography.css\":1,\"sites\\/all\\/themes\\/fusion\\/fusion_core\\/skins\\/core\\/fusion-core-skins.css\":1,\"sites\\/all\\/themes\\/fusion\\/ateneo\\/css\\/ateneo.css\":1,\"sites\\/all\\/themes\\/fusion\\/ateneo\\/css\\/lor-main.css\":1,\"sites\\/all\\/themes\\/fusion\\/ateneo\\/css\\/ateneo-blocks.css\":1,\"sites\\/all\\/themes\\/fusion\\/ateneo\\/css\\/fusion-starter-style.css\":1,\"sites\\/all\\/themes\\/fusion\\/ateneo\\/css\\/bgstretcher.css\":1,\"sites\\/all\\/themes\\/fusion\\/fusion_core\\/css\\/grid12-960.css\":1,\"public:\\/\\/css_injector\\/css_injector_6.css\":1,\"public:\\/\\/css_injector\\/css_injector_11.css\":1,\"public:\\/\\/css_injector\\/css_injector_14.css\":1,\"public:\\/\\/css_injector\\/css_injector_18.css\":1,\"public:\\/\\/css_injector\\/css_injector_21.css\":1,\"public:\\/\\/css_injector\\/css_injector_22.css\":1,\"public:\\/\\/css_injector\\/css_injector_37.css\":1,\"public:\\/\\/css_injector\\/css_injector_40.css\":1,\"public:\\/\\/css_injector\\/css_injector_41.css\":1,\"public:\\/\\/css_injector\\/css_injector_43.css\":1,\"public:\\/\\/css_injector\\/css_injector_44.css\":1,\"public:\\/\\/css_injector\\/css_injector_46.css\":1,\"public:\\/\\/css_injector\\/css_injector_49.css\":1,\"public:\\/\\/css_injector\\/css_injector_51.css\":1,\"public:\\/\\/css_injector\\/css_injector_62.css\":1,\"public:\\/\\/css_injector\\/css_injector_67.css\":1,\"public:\\/\\/css_injector\\/css_injector_70.css\":1,\"public:\\/\\/css_injector\\/css_injector_79.css\":1,\"public:\\/\\/css_injector\\/css_injector_100.css\":1,\"public:\\/\\/css_injector\\/css_injector_105.css\":1}},\"colorbox\":{\"transition\":\"elastic\",\"speed\":\"350\",\"opacity\":\"0.30\",\"slideshow\":false,\"slideshowAuto\":true,\"slideshowSpeed\":\"2500\",\"slideshowStart\":\"start slideshow\",\"slideshowStop\":\"stop slideshow\",\"current\":\"{current} of {total}\",\"previous\":\"\\u00ab Prev\",\"next\":\"Next \\u00bb\",\"close\":\"Close\",\"overlayClose\":true,\"maxWidth\":\"85%\",\"maxHeight\":\"85%\",\"initialWidth\":\"300\",\"initialHeight\":\"100\",\"fixed\":true,\"scrolling\":true,\"__drupal_alter_by_ref\":[\"stockholmsyndrome\"]},\"cufonSelectors\":[],\"simpleDialog\":{\"classes\":\"soss-announcement\",\"defaults\":\"width:300;height:auto;position:[center,60]\",\"selector\":\"\",\"title\":\"Announcement\"},\"custom_search\":{\"form_target\":\"_self\",\"solr\":0},\"viewsSlideshow\":{\"anouncement_ticker-block\":{\"methods\":{\"goToSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"nextSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"pause\":[\"viewsSlideshowControls\",\"viewsSlideshowCycle\"],\"play\":[\"viewsSlideshowControls\",\"viewsSlideshowCycle\"],\"previousSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"transitionBegin\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\"],\"transitionEnd\":[]},\"paused\":0},\"admissions_slideshow-block\":{\"methods\":{\"goToSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"nextSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"pause\":[\"viewsSlideshowControls\",\"viewsSlideshowCycle\"],\"play\":[\"viewsSlideshowControls\",\"viewsSlideshowCycle\"],\"previousSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"transitionBegin\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\"],\"transitionEnd\":[]},\"paused\":0},\"anouncement_ticker-block_2\":{\"methods\":{\"goToSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"nextSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"pause\":[\"viewsSlideshowControls\",\"viewsSlideshowCycle\"],\"play\":[\"viewsSlideshowControls\",\"viewsSlideshowCycle\"],\"previousSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"transitionBegin\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\"],\"transitionEnd\":[]},\"paused\":0},\"admissions_slideshow-block_2\":{\"methods\":{\"goToSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"nextSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"pause\":[\"viewsSlideshowControls\",\"viewsSlideshowCycle\"],\"play\":[\"viewsSlideshowControls\",\"viewsSlideshowCycle\"],\"previousSlide\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\",\"viewsSlideshowCycle\"],\"transitionBegin\":[\"viewsSlideshowPager\",\"viewsSlideshowSlideCounter\"],\"transitionEnd\":[]},\"paused\":0}},\"viewsSlideshowCycle\":{\"#views_slideshow_cycle_main_anouncement_ticker-block\":{\"num_divs\":3,\"id_prefix\":\"#views_slideshow_cycle_main_\",\"div_prefix\":\"#views_slideshow_cycle_div_\",\"vss_id\":\"anouncement_ticker-block\",\"effect\":\"scrollLeft\",\"transition_advanced\":1,\"timeout\":5000,\"speed\":2000,\"delay\":0,\"sync\":1,\"random\":0,\"pause\":1,\"pause_on_click\":0,\"action_advanced\":0,\"start_paused\":0,\"remember_slide\":0,\"remember_slide_days\":1,\"pause_when_hidden\":0,\"pause_when_hidden_type\":\"full\",\"amount_allowed_visible\":\"\",\"nowrap\":0,\"fixed_height\":1,\"items_per_slide\":1,\"wait_for_image_load\":1,\"wait_for_image_load_timeout\":3000,\"cleartype\":0,\"cleartypenobg\":0,\"advanced_options\":\"{}\",\"advanced_options_choices\":0,\"advanced_options_entry\":\"\"},\"#views_slideshow_cycle_main_admissions_slideshow-block\":{\"num_divs\":7,\"id_prefix\":\"#views_slideshow_cycle_main_\",\"div_prefix\":\"#views_slideshow_cycle_div_\",\"vss_id\":\"admissions_slideshow-block\",\"effect\":\"fade\",\"transition_advanced\":0,\"timeout\":5000,\"speed\":700,\"delay\":0,\"sync\":1,\"random\":0,\"pause\":1,\"pause_on_click\":0,\"action_advanced\":0,\"start_paused\":0,\"remember_slide\":0,\"remember_slide_days\":1,\"pause_when_hidden\":0,\"pause_when_hidden_type\":\"full\",\"amount_allowed_visible\":\"\",\"nowrap\":0,\"fixed_height\":1,\"items_per_slide\":1,\"wait_for_image_load\":1,\"wait_for_image_load_timeout\":3000,\"cleartype\":0,\"cleartypenobg\":0,\"advanced_options\":\"{}\",\"advanced_options_choices\":0,\"advanced_options_entry\":\"\"},\"#views_slideshow_cycle_main_anouncement_ticker-block_2\":{\"num_divs\":3,\"id_prefix\":\"#views_slideshow_cycle_main_\",\"div_prefix\":\"#views_slideshow_cycle_div_\",\"vss_id\":\"anouncement_ticker-block_2\",\"effect\":\"scrollLeft\",\"transition_advanced\":1,\"timeout\":5000,\"speed\":2000,\"delay\":0,\"sync\":1,\"random\":0,\"pause\":1,\"pause_on_click\":0,\"action_advanced\":0,\"start_paused\":0,\"remember_slide\":0,\"remember_slide_days\":1,\"pause_when_hidden\":0,\"pause_when_hidden_type\":\"full\",\"amount_allowed_visible\":\"\",\"nowrap\":0,\"fixed_height\":1,\"items_per_slide\":1,\"wait_for_image_load\":1,\"wait_for_image_load_timeout\":3000,\"cleartype\":0,\"cleartypenobg\":0,\"advanced_options\":\"{}\",\"advanced_options_choices\":0,\"advanced_options_entry\":\"\"},\"#views_slideshow_cycle_main_admissions_slideshow-block_2\":{\"num_divs\":7,\"id_prefix\":\"#views_slideshow_cycle_main_\",\"div_prefix\":\"#views_slideshow_cycle_div_\",\"vss_id\":\"admissions_slideshow-block_2\",\"effect\":\"fade\",\"transition_advanced\":0,\"timeout\":5000,\"speed\":700,\"delay\":0,\"sync\":1,\"random\":0,\"pause\":1,\"pause_on_click\":0,\"action_advanced\":0,\"start_paused\":0,\"remember_slide\":0,\"remember_slide_days\":1,\"pause_when_hidden\":0,\"pause_when_hidden_type\":\"full\",\"amount_allowed_visible\":\"\",\"nowrap\":0,\"fixed_height\":1,\"items_per_slide\":1,\"wait_for_image_load\":1,\"wait_for_image_load_timeout\":3000,\"cleartype\":0,\"cleartypenobg\":0,\"advanced_options\":\"{}\",\"advanced_options_choices\":0,\"advanced_options_entry\":\"\"}},\"views\":{\"ajax_path\":\"\\/views\\/ajax\",\"ajaxViews\":{\"views_dom_id:39adfb3ccbbac091fe75492fbedb7541\":{\"view_name\":\"profile_publication\",\"view_display_id\":\"block\",\"view_args\":\"4797\",\"view_path\":\"node\\/4797\",\"view_base_path\":null,\"view_dom_id\":\"39adfb3ccbbac091fe75492fbedb7541\",\"pager_element\":\"0\"},\"views_dom_id:7f3a50908efe369d9fabd60214ed135c\":{\"view_name\":\"admissions_slideshow\",\"view_display_id\":\"block\",\"view_args\":\"\",\"view_path\":\"node\\/4797\",\"view_base_path\":\"ls\\/undergraduate\\/news-archive\",\"view_dom_id\":\"7f3a50908efe369d9fabd60214ed135c\",\"pager_element\":0},\"views_dom_id:6d9e22294fd3a6d6083686208e4f8765\":{\"view_name\":\"profile_publication\",\"view_display_id\":\"block\",\"view_args\":\"4797\",\"view_path\":\"node\\/4797\",\"view_base_path\":null,\"view_dom_id\":\"6d9e22294fd3a6d6083686208e4f8765\",\"pager_element\":\"0\"},\"views_dom_id:70165a148e1b657aa679a41502c88995\":{\"view_name\":\"admissions_slideshow\",\"view_display_id\":\"block\",\"view_args\":\"\",\"view_path\":\"node\\/4797\",\"view_base_path\":\"ls\\/undergraduate\\/news-archive\",\"view_dom_id\":\"70165a148e1b657aa679a41502c88995\",\"pager_element\":0}}},\"viewsSlideshowControls\":{\"admissions_slideshow-block\":{\"bottom\":{\"type\":\"viewsSlideshowControlsText\"}},\"admissions_slideshow-block_2\":{\"bottom\":{\"type\":\"viewsSlideshowControlsText\"}}},\"responsive_menus\":[{\"toggler_text\":\"Menu \\u2630\",\"selectors\":[\"#block-menu-menu-law-school-menu\",\"#block-superfish-47\"],\"media_size\":\"959\",\"remove_attributes\":true,\"responsive_menus_style\":\"responsive_menus_simple\"}],\"googleanalytics\":{\"trackOutbound\":1,\"trackMailto\":1,\"trackDownload\":1,\"trackDownloadExtensions\":\"7z|aac|arc|arj|asf|asx|avi|bin|csv|doc|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls|xml|z|zip\"},\"urlIsAjaxTrusted\":{\"\\/admissions\":true}});\n"
                + "//--><!]]>\n"
                + "</script>\n"
                + "\n"
                + "</head>\n"
                + "<body id=\"pid-admissions\" class=\"html not-front not-logged-in no-sidebars page-node page-node- page-node-4797 node-type-page chrome chrome76 win desktop font-size-13 grid-type-960 grid-width-12 sidebars-split\" >\n"
                + "  <div id=\"skip-link\">\n"
                + "    <a href=\"#main-content-area\">Skip to main content area</a>\n"
                + "  </div>\n"
                + "    \n"
                + "\n"
                + "	    	\n"
                + "		<style type=\"text/css\">\n"
                + "            html.js div.contextual-links-wrapper,\n"
                + "			#content-tabs{\n"
                + "                display:block;\n"
                + "            }\n"
                + "        </style>\n"
                + "	\n"
                + "<script type=\"text/javascript\">\n"
                + "(function($){ 		\n"
                + "	//$.backstretch(\"/sites/all/themes/fusion/ateneo/images/plain-blue.jpg\");\n"
                + "	$.backstretch(\"/sites/all/themes/fusion/highschool/images/hshighschool-bg.jpg\");\n"
                + "})(jQuery);\n"
                + "</script>\n"
                + "\n"
                + "  <div id=\"page\" class=\"page\">\n"
                + "    <div id=\"page-inner\" class=\"page-inner\">\n"
                + "      \n"
                + "      <!-- header-group region: width = grid_width -->\n"
                + "      <div id=\"header-group-wrapper\" class=\"header-group-wrapper full-width clearfix\">\n"
                + "        <div id=\"header-group\" class=\"header-group region grid12-12\">\n"
                + "          <div id=\"header-group-inner\" class=\"header-group-inner inner clearfix\">\n"
                + "\n"
                + "                        <div id=\"header-site-info\" class=\"header-site-info clearfix\">\n"
                + "              <div id=\"header-site-info-inner\" class=\"header-site-info-inner gutter\">\n"
                + "                                <div id=\"logo\">\n"
                + "                  <a href=\"/\" title=\"Ateneo de Manila University Home\"><img src=\"https://ateneo.edu/sites/default/files/logo_0.png\" alt=\"Ateneo de Manila University Home\" /></a>\n"
                + "                </div>\n"
                + "                                              </div><!-- /header-site-info-inner -->\n"
                + "            </div><!-- /header-site-info -->\n"
                + "            \n"
                + "            <div id=\"block-superfish-18\" class=\"block block-superfish first  odd\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <ul id=\"superfish-18\" class=\"sf-menu menu-main-upper-menu sf-horizontal sf-style-none sf-total-items-3 sf-parent-items-1 sf-single-items-2\"><li id=\"menu-2952-18\" class=\"first odd sf-item-1 sf-depth-1 sf-no-children\"><a href=\"/about-us\" class=\"sf-depth-1 \">ABOUT ATENEO</a></li><li id=\"menu-2953-18\" class=\"middle even sf-item-2 sf-depth-1 sf-no-children\"><a href=\"/index\" class=\"sf-depth-1 \">INDEX</a></li><li id=\"menu-2954-18\" class=\"last odd sf-item-3 sf-depth-1 sf-total-children-4 sf-parent-children-3 sf-single-children-1 menuparent\"><span class=\"sf-depth-1  menuparent nolink\">SCHOOLS</span><ul><li id=\"menu-8258-18\" class=\"first odd sf-item-1 sf-depth-2 sf-total-children-3 sf-parent-children-0 sf-single-children-3 menuparent\"><a href=\"/basic-ed\" class=\"sf-depth-2  menuparent\">Basic Education</a><ul><li id=\"menu-2955-18\" class=\"first odd sf-item-1 sf-depth-3 sf-no-children\"><a href=\"/grade-school\" class=\"sf-depth-3 \">Grade School</a></li><li id=\"menu-5055-18\" class=\"middle even sf-item-2 sf-depth-3 sf-no-children\"><a href=\"/ajhs\" class=\"sf-depth-3 \">Junior High School</a></li><li id=\"menu-2956-18\" class=\"last odd sf-item-3 sf-depth-3 sf-no-children\"><a href=\"/high-school\" class=\"sf-depth-3 \">Senior High School</a></li></ul></li><li id=\"menu-2957-18\" class=\"middle even sf-item-2 sf-depth-2 sf-total-children-4 sf-parent-children-0 sf-single-children-4 menuparent\"><a href=\"/ls\" class=\"sf-depth-2  menuparent\">Loyola Schools</a><ul><li id=\"menu-2959-18\" class=\"first odd sf-item-1 sf-depth-3 sf-no-children\"><a href=\"/ls/jgsom\" class=\"sf-depth-3 \">John Gokongwei School of Management</a></li><li id=\"menu-2958-18\" class=\"middle even sf-item-2 sf-depth-3 sf-no-children\"><a href=\"/ls/soh\" class=\"sf-depth-3 \">School of Humanities</a></li><li id=\"menu-2960-18\" class=\"middle odd sf-item-3 sf-depth-3 sf-no-children\"><a href=\"/ls/sose\" class=\"sf-depth-3 \">School of Science and Engineering</a></li><li id=\"menu-2961-18\" class=\"last even sf-item-4 sf-depth-3 sf-no-children\"><a href=\"/ls/soss\" class=\"sf-depth-3 \">School of Social Sciences</a></li></ul></li><li id=\"menu-4877-18\" class=\"middle odd sf-item-3 sf-depth-2 sf-no-children\"><a href=\"/ls/graduate/graduate-programs\" class=\"sf-depth-2 \">LS Graduate Programs</a></li><li id=\"menu-2962-18\" class=\"last even sf-item-4 sf-depth-2 sf-total-children-5 sf-parent-children-0 sf-single-children-5 menuparent\"><a href=\"/aps\" class=\"sf-depth-2  menuparent\">Professional Schools</a><ul><li id=\"menu-2963-18\" class=\"first odd sf-item-1 sf-depth-3 sf-no-children\"><a href=\"http://gsb.ateneo.edu\" class=\"sf-depth-3 \">Ateneo Graduate School of Business</a></li><li id=\"menu-2964-18\" class=\"middle even sf-item-2 sf-depth-3 sf-no-children\"><a href=\"http://ateneo.edu/aps/law\" class=\"sf-depth-3 \">Ateneo Law School</a></li><li id=\"menu-2965-18\" class=\"middle odd sf-item-3 sf-depth-3 sf-no-children\"><a href=\"/aps/asog\" class=\"sf-depth-3 \">Ateneo School of Government</a></li><li id=\"menu-2966-18\" class=\"middle even sf-item-4 sf-depth-3 sf-no-children\"><a href=\"/aps/asmph\" class=\"sf-depth-3 \">Ateneo School of Medicine and Public Health</a></li><li id=\"menu-9144-18\" class=\"last odd sf-item-5 sf-depth-3 sf-no-children\"><a href=\"http://aps-research.ateneo.edu/\" class=\"sf-depth-3 \">APS Research</a></li></ul></li></ul></li></ul>    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "<div id=\"block-custom_search_blocks-1\" class=\"block block-custom-search-blocks  last even\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <form class=\"search-form\" action=\"/admissions\" method=\"post\" id=\"custom-search-blocks-form-1\" accept-charset=\"UTF-8\"><div><div class=\"form-item form-type-textfield form-item-custom-search-blocks-form-1\">\n"
                + "  <input class=\"custom-search-default-value custom-search-box form-text\" type=\"text\" id=\"edit-custom-search-blocks-form-1--2\" name=\"custom_search_blocks_form_1\" value=\"\" size=\"15\" maxlength=\"128\" />\n"
                + "</div>\n"
                + "<fieldset class=\"custom_search-popup form-wrapper\" id=\"edit-popup\"><div class=\"fieldset-wrapper\"></div></fieldset>\n"
                + "<input type=\"hidden\" name=\"delta\" value=\"1\" />\n"
                + "<input type=\"hidden\" name=\"form_build_id\" value=\"form-YbbDx_m4qatSuiIhcupGk9Mv4uFjwNrMea4Ct8dpStQ\" />\n"
                + "<input type=\"hidden\" name=\"form_id\" value=\"custom_search_blocks_form_1\" />\n"
                + "<input class=\"default-text\" type=\"hidden\" name=\"default_text\" value=\"\" />\n"
                + "<div class=\"form-actions form-wrapper\" id=\"edit-actions\"><input type=\"submit\" id=\"edit-submit\" name=\"op\" value=\"Search\" class=\"form-submit\" /></div></div></form>    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "                      </div><!-- /header-group-inner -->\n"
                + "        </div><!-- /header-group -->\n"
                + "      </div><!-- /header-group-wrapper -->\n"
                + "\n"
                + "      \n"
                + "<!-- preface-top region -->\n"
                + "<div id=\"preface-top-wrapper\" class=\"preface-top-wrapper full-width clearfix\">\n"
                + "  <div id=\"preface-top\" class=\"region region-preface-top preface-top  grid12-12\">\n"
                + "    <div id=\"preface-top-inner\" class=\"preface-top-inner inner\">\n"
                + "      <div id=\"block-superfish-5\" class=\"block block-superfish first  odd\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <ul id=\"superfish-5\" class=\"sf-menu menu-main-navigation sf-horizontal sf-style-none sf-total-items-8 sf-parent-items-0 sf-single-items-8\"><li id=\"menu-4023-5\" class=\"first odd sf-item-1 sf-depth-1 sf-no-children\"><a href=\"/\" class=\"sf-depth-1 \">Home</a></li><li id=\"menu-1542-5\" class=\"active-trail middle even sf-item-2 sf-depth-1 sf-no-children\"><a href=\"/admissions\" class=\"sf-depth-1  active\">Admissions</a></li><li id=\"menu-1543-5\" class=\"middle odd sf-item-3 sf-depth-1 sf-no-children\"><a href=\"/ateneo-student-life\" class=\"sf-depth-1 \">Student Life</a></li><li id=\"menu-8226-5\" class=\"middle even sf-item-4 sf-depth-1 sf-no-children\"><a href=\"/university-research\" class=\"sf-depth-1 \">Research</a></li><li id=\"menu-1545-5\" class=\"middle odd sf-item-5 sf-depth-1 sf-no-children\"><a href=\"http://global.ateneo.edu\" class=\"sf-depth-1 \">Global</a></li><li id=\"menu-1546-5\" class=\"middle even sf-item-6 sf-depth-1 sf-no-children\"><a href=\"/social-development\" class=\"sf-depth-1 \">Social Development</a></li><li id=\"menu-4702-5\" class=\"middle odd sf-item-7 sf-depth-1 sf-no-children\"><a href=\"/alumni\" class=\"sf-depth-1 \">Alumni</a></li><li id=\"menu-8136-5\" class=\"last even sf-item-8 sf-depth-1 sf-no-children\"><a href=\"/giving\" class=\"sf-depth-1 \">Giving</a></li></ul>    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "<div id=\"block-views-anouncement_ticker-block\" class=\"block block-views  last even\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <div class=\"view view-anouncement-ticker view-id-anouncement_ticker view-display-id-block view-dom-id-e8d3fa801d2cc1f669d03283aaa0c4d6\">\n"
                + "        \n"
                + "  \n"
                + "  \n"
                + "      <div class=\"view-content\">\n"
                + "      \n"
                + "<div class=\"skin-default\">\n"
                + "  \n"
                + "  <div id=\"views_slideshow_cycle_main_anouncement_ticker-block\" class=\"views_slideshow_cycle_main views_slideshow_main\"><div id=\"views_slideshow_cycle_teaser_section_anouncement_ticker-block\" class=\"views-slideshow-cycle-main-frame views_slideshow_cycle_teaser_section\">\n"
                + "  <div id=\"views_slideshow_cycle_div_anouncement_ticker-block_0\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-1 views-row-odd\">\n"
                + "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-first views-row-odd\">\n"
                + "    \n"
                + "  <div class=\"views-field views-field-title\">        <span class=\"field-content\"><a href=\"/news/grade-11-applications-ongoing\">Grade 11 applications ongoing</a></span>  </div></div>\n"
                + "</div>\n"
                + "<div id=\"views_slideshow_cycle_div_anouncement_ticker-block_1\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-2 views_slideshow_cycle_hidden views-row-even\">\n"
                + "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-first views-row-odd\">\n"
                + "    \n"
                + "  <div class=\"views-field views-field-title\">        <span class=\"field-content\"><a href=\"/news/grade-7-applications-ongoing\">Grade 7 applications ongoing</a></span>  </div></div>\n"
                + "</div>\n"
                + "<div id=\"views_slideshow_cycle_div_anouncement_ticker-block_2\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-3 views_slideshow_cycle_hidden views-row-odd\">\n"
                + "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-first views-row-odd\">\n"
                + "    \n"
                + "  <div class=\"views-field views-field-title\">        <span class=\"field-content\"><a href=\"/news/read-university-policy-anti-sexual-harassment\">Read the University&#039;s Anti-Sexual Harassment Policy.</a></span>  </div></div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "  </div>\n"
                + "    </div>\n"
                + "  \n"
                + "  \n"
                + "  \n"
                + "  \n"
                + "  \n"
                + "  \n"
                + "</div>    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "    </div><!-- /preface-top-inner -->\n"
                + "  </div><!-- /preface-top -->\n"
                + "</div><!-- /preface-top-wrapper -->\n"
                + "\n"
                + "      <!-- main region: width = grid_width -->\n"
                + "      <div id=\"main-wrapper\" class=\"main-wrapper full-width clearfix\">\n"
                + "        <div id=\"main\" class=\"main region grid12-12\">\n"
                + "          <div id=\"main-inner\" class=\"main-inner inner clearfix\">\n"
                + "            \n"
                + "            <!-- main group: width = grid_width - sidebar_first_width -->\n"
                + "            <div id=\"main-group\" class=\"main-group region nested grid12-12\">\n"
                + "              <div id=\"main-group-inner\" class=\"main-group-inner inner\">\n"
                + "                \n"
                + "                <div id=\"main-content\" class=\"main-content region nested\">\n"
                + "                  <div id=\"main-content-inner\" class=\"main-content-inner inner\">\n"
                + "                    <!-- content group: width = grid_width - sidebar_first_width - sidebar_second_width -->\n"
                + "                    <div id=\"content-group\" class=\"content-group region nested grid12-12\">\n"
                + "                      <div id=\"content-group-inner\" class=\"content-group-inner inner\">\n"
                + "                        <div id=\"breadcrumbs\" class=\"breadcrumbs block\">\n"
                + "<div id=\"breadcrumbs-inner\" class=\"breadcrumbs-inner gutter\">\n"
                + "<h2 class=\"element-invisible\">You are here</h2><div class=\"breadcrumb\"><div class=\"inline odd first\" itemscope itemtype=\"http://data-vocabulary.org/Breadcrumb\"><a href=\"https://ateneo.edu/\" itemprop=\"url\"><span itemprop=\"title\">Home</span></a></div> » <div class=\"inline even last\" itemscope itemtype=\"http://data-vocabulary.org/Breadcrumb\"><span itemprop=\"title\">Admissions</span></div></div></div><!-- /breadcrumbs-inner -->\n"
                + "</div><!-- /breadcrumbs -->\n"
                + "                        \n"
                + "                        <div id=\"content-region\" class=\"content-region region nested\">\n"
                + "                          <div id=\"content-region-inner\" class=\"content-region-inner inner\">\n"
                + "                            <a id=\"main-content-area\"></a>\n"
                + "                                                                                                                                            <h1 class=\"title gutter\">Admissions</h1>\n"
                + "                                                                                                                                              \n"
                + "<!-- content region -->\n"
                + "  <div id=\"content\" class=\"region region-content content nested grid12-12\">\n"
                + "    <div id=\"content-inner\" class=\"content-inner inner\">\n"
                + "      <div id=\"block-system-main\" class=\"block block-system display-none fusion-callout first  odd\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <div id=\"node-4797\" class=\"node node-page odd full-node clearfix\" about=\"/admissions\" typeof=\"foaf:Document\">\n"
                + "  \n"
                + "      <span property=\"dc:title\" content=\"Admissions\" class=\"rdf-meta element-hidden\"></span>\n"
                + "  \n"
                + "      <div id=\"node-top\" class=\"node-top region nested\">\n"
                + "          </div>\n"
                + "    \n"
                + "  <div class=\"content\">\n"
                + "    <div class=\"field field-name-body field-type-text-with-summary field-label-hidden\"><div class=\"field-items\"><div class=\"field-item even\" property=\"content:encoded\"><p>We will dare you to discover a larger vision of yourself and our world. We will challenge you to do \"the things of greater worth\" because we know you are more than what the grade-givers of this world make you out to be. We do this because the Ateneo is more than just a school.</p>\n"
                + "<div class=\"welcome\" style=\"float: right; margin-top: 30px;\">\n"
                + "	WELCOME</div>\n"
                + "</div></div></div>  </div>\n"
                + "\n"
                + "  \n"
                + "  \n"
                + "      <div id=\"node-bottom\" class=\"node-bottom region nested\">\n"
                + "          </div>\n"
                + "    \n"
                + "</div>\n"
                + "    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "<div id=\"block-views-admissions_slideshow-block\" class=\"block block-views   even\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <div class=\"view view-admissions-slideshow view-id-admissions_slideshow view-display-id-block view-dom-id-7f3a50908efe369d9fabd60214ed135c\">\n"
                + "        \n"
                + "  \n"
                + "  \n"
                + "      <div class=\"view-content\">\n"
                + "      \n"
                + "<div class=\"skin-default\">\n"
                + "  \n"
                + "  <div id=\"views_slideshow_cycle_main_admissions_slideshow-block\" class=\"views_slideshow_cycle_main views_slideshow_main\"><div id=\"views_slideshow_cycle_teaser_section_admissions_slideshow-block\" class=\"views-slideshow-cycle-main-frame views_slideshow_cycle_teaser_section\">\n"
                + "  <div id=\"views_slideshow_cycle_div_admissions_slideshow-block_0\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-1 views-row-odd\">\n"
                + "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-first views-row-odd\">\n"
                + "    \n"
                + "  <div class=\"views-field views-field-field-page-img\">        <div class=\"field-content\"><img typeof=\"foaf:Image\" src=\"https://ateneo.edu/sites/default/files/styles/admissions_385x220/public/page-image/St.%20Ignatius.jpg?itok=taRWjuDA\" width=\"385\" height=\"220\" alt=\"\" /></div>  </div></div>\n"
                + "</div>\n"
                + "<div id=\"views_slideshow_cycle_div_admissions_slideshow-block_1\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-2 views_slideshow_cycle_hidden views-row-even\">\n"
                + "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-first views-row-odd\">\n"
                + "    \n"
                + "  <div class=\"views-field views-field-field-page-img\">        <div class=\"field-content\"><img typeof=\"foaf:Image\" src=\"https://ateneo.edu/sites/default/files/styles/admissions_385x220/public/page-image/f_0.jpg?itok=i4yytDs6\" width=\"385\" height=\"220\" alt=\"\" /></div>  </div></div>\n"
                + "</div>\n"
                + "<div id=\"views_slideshow_cycle_div_admissions_slideshow-block_2\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-3 views_slideshow_cycle_hidden views-row-odd\">\n"
                + "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-first views-row-odd\">\n"
                + "    \n"
                + "  <div class=\"views-field views-field-field-page-img\">        <div class=\"field-content\"><img typeof=\"foaf:Image\" src=\"https://ateneo.edu/sites/default/files/styles/admissions_385x220/public/page-image/e.jpg?itok=46YIO2fp\" width=\"385\" height=\"220\" alt=\"\" /></div>  </div></div>\n"
                + "</div>\n"
                + "<div id=\"views_slideshow_cycle_div_admissions_slideshow-block_3\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-4 views_slideshow_cycle_hidden views-row-even\">\n"
                + "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-first views-row-odd\">\n"
                + "    \n"
                + "  <div class=\"views-field views-field-field-page-img\">        <div class=\"field-content\"><img typeof=\"foaf:Image\" src=\"https://ateneo.edu/sites/default/files/styles/admissions_385x220/public/page-image/a_2.jpg?itok=WfMcmviw\" width=\"385\" height=\"220\" alt=\"\" /></div>  </div></div>\n"
                + "</div>\n"
                + "<div id=\"views_slideshow_cycle_div_admissions_slideshow-block_4\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-5 views_slideshow_cycle_hidden views-row-odd\">\n"
                + "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-first views-row-odd\">\n"
                + "    \n"
                + "  <div class=\"views-field views-field-field-page-img\">        <div class=\"field-content\"><img typeof=\"foaf:Image\" src=\"https://ateneo.edu/sites/default/files/styles/admissions_385x220/public/page-image/c.jpg?itok=uCRibk4y\" width=\"385\" height=\"220\" alt=\"\" /></div>  </div></div>\n"
                + "</div>\n"
                + "<div id=\"views_slideshow_cycle_div_admissions_slideshow-block_5\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-6 views_slideshow_cycle_hidden views-row-even\">\n"
                + "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-first views-row-odd\">\n"
                + "    \n"
                + "  <div class=\"views-field views-field-field-page-img\">        <div class=\"field-content\"><img typeof=\"foaf:Image\" src=\"https://ateneo.edu/sites/default/files/styles/admissions_385x220/public/page-image/d.jpg?itok=Mx2vtHkR\" width=\"385\" height=\"220\" alt=\"\" /></div>  </div></div>\n"
                + "</div>\n"
                + "<div id=\"views_slideshow_cycle_div_admissions_slideshow-block_6\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-7 views_slideshow_cycle_hidden views-row-odd\">\n"
                + "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-first views-row-odd\">\n"
                + "    \n"
                + "  <div class=\"views-field views-field-field-page-img\">        <div class=\"field-content\"><img typeof=\"foaf:Image\" src=\"https://ateneo.edu/sites/default/files/styles/admissions_385x220/public/page-image/b.jpg?itok=0IZk--vB\" width=\"385\" height=\"220\" alt=\"\" /></div>  </div></div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "      <div class=\"views-slideshow-controls-bottom clearfix\">\n"
                + "      <div id=\"views_slideshow_controls_text_admissions_slideshow-block\" class=\"views-slideshow-controls-text views_slideshow_controls_text\">\n"
                + "  <span id=\"views_slideshow_controls_text_previous_admissions_slideshow-block\" class=\"views-slideshow-controls-text-previous views_slideshow_controls_text_previous\"><a href=\"#\">Previous</a></span>\n"
                + "  <span id=\"views_slideshow_controls_text_pause_admissions_slideshow-block\" class=\"views-slideshow-controls-text-pause views_slideshow_controls_text_pause\"><a href=\"#\">Pause</a></span>\n"
                + "  <span id=\"views_slideshow_controls_text_next_admissions_slideshow-block\" class=\"views-slideshow-controls-text-next views_slideshow_controls_text_next\"><a href=\"#\">Next</a></span>\n"
                + "</div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "    </div>\n"
                + "  \n"
                + "  \n"
                + "  \n"
                + "  \n"
                + "  \n"
                + "  \n"
                + "</div>    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "<div id=\"block-block-98\" class=\"block block-block  last odd\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <div class=\"menu-left\" style=\"float:left; border-right: 2px solid #eec041; padding-right: 35px; height: 200px;\">\n"
                + "<div class=\"heading\">\n"
                + "<h2>\n"
                + "			<span style=\"color:#084a85;\">Basic Education</span></h2>\n"
                + "</div>\n"
                + "<ul><li>\n"
                + "			<a href=\"/grade-school/application-sy-2019-2020\" target=\"_blank\">GRADE SCHOOL</a></li>\n"
                + "<li>\n"
                + "			<a href=\"/ajhs/admissions\" target=\"_blank\">JUNIOR HIGH SCHOOL</a></li>\n"
                + "<li>\n"
                + "			<a href=\"/high-school/admissions\" target=\"_blank\">SENIOR HIGH SCHOOL</a></li>\n"
                + "</ul></div>\n"
                + "<div class=\"menu-middle\" style=\"float:left; border-right: 2px solid #eec041; padding-right: 35px; padding-left: 15px; height: 200px;\">\n"
                + "<div class=\"heading\">\n"
                + "<h2>\n"
                + "			<span style=\"color:#084a85;\">Loyola Schools</span></h2>\n"
                + "</div>\n"
                + "<ul><li>\n"
                + "			<a href=\"/ls/undergraduate-programs\">UNDERGRADUATE PROGRAMS</a></li>\n"
                + "<li>\n"
                + "			<a href=\"/ls/graduate-programs\" target=\"_blank\">GRADUATE PROGRAMS</a></li>\n"
                + "</ul></div>\n"
                + "<div class=\"menu-right\" style=\"float:left; padding-left: 15px; height: 200px;\">\n"
                + "<div class=\"heading\">\n"
                + "<h2>\n"
                + "			<span style=\"color:#084a85;\">Professional Schools</span></h2>\n"
                + "</div>\n"
                + "<ul><li>\n"
                + "			<a href=\"/professional-schools/ateneo-law-school\" target=\"_blank\">ATENEO LAW SCHOOL</a></li>\n"
                + "<li>\n"
                + "			<a href=\"/professional-schools/agsb\" target=\"_blank\">ATENEO GRADUATE SCHOOL OF<br />\n"
                + "			   BUSINESS</a></li>\n"
                + "<li>\n"
                + "			<a href=\"/aps/asog\" target=\"_blank\">ATENEO SCHOOL OF GOVERNMENT</a></li>\n"
                + "<li>\n"
                + "			<a href=\"/professional-schools/asmph\" target=\"_blank\">ATENEO SCHOOL OF MEDICINE AND<br />\n"
                + "			   PUBLIC HEALTH</a></li>\n"
                + "</ul></div>\n"
                + "<p></p>\n"
                + "    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "    </div><!-- /content-inner -->\n"
                + "  </div><!-- /content -->\n"
                + "                                                      </div><!-- /content-region-inner -->\n"
                + "                        </div><!-- /content-region -->\n"
                + "\n"
                + "                      </div><!-- /content-group-inner -->\n"
                + "                    </div><!-- /content-group -->\n"
                + "                                      </div><!-- /main-content-inner -->\n"
                + "                </div><!-- /main-content -->\n"
                + "\n"
                + "                              </div><!-- /main-group-inner -->\n"
                + "            </div><!-- /main-group -->\n"
                + "          </div><!-- /main-inner -->\n"
                + "        </div><!-- /main -->\n"
                + "      </div><!-- /main-wrapper -->\n"
                + "\n"
                + "            \n"
                + "<!-- footer region -->\n"
                + "<div id=\"footer-wrapper\" class=\"footer-wrapper full-width clearfix\">\n"
                + "  <div id=\"footer\" class=\"region region-footer footer  grid12-12\">\n"
                + "    <div id=\"footer-inner\" class=\"footer-inner inner\">\n"
                + "      <div id=\"block-menu-menu-main-left-footer\" class=\"block block-menu first  odd\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <ul class=\"menu\"><li class=\"first leaf\"><a href=\"http://www.ateneo.edu/basic-ed\" target=\"_blank\">Basic Education Unit</a></li>\n"
                + "<li class=\"leaf\"><a href=\"/ls\" class=\"white-arrow\" target=\"_blank\">Loyola Schools</a></li>\n"
                + "<li class=\"leaf\"><a href=\"/ls/graduate/graduate-programs\" target=\"_blank\">LS Graduate Programs</a></li>\n"
                + "<li class=\"leaf\"><a href=\"/aps\" target=\"_blank\">Professional Schools</a></li>\n"
                + "<li class=\"leaf\"><a href=\"http://www.ateneo.edu/central-administration\" class=\"offices\" target=\"_blank\">Administrative Offices</a></li>\n"
                + "<li class=\"leaf\"><a href=\"http://www.ateneo.edu/campus-maps\" target=\"_blank\">Campus Maps</a></li>\n"
                + "<li class=\"last leaf\"><a href=\"http://www.ateneo.edu/ateneo-campus-directory\" target=\"_blank\">Directory</a></li>\n"
                + "</ul>    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "<div id=\"block-block-3\" class=\"block block-block   even\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <p><a href=\"https://www.ateneo.edu/uaap\" target=\"_blank\"><img alt=\"\" src=\"/sites/default/files/Website%20Footer.png\" style=\"width: 439px; height: 109px;\" /></a></p>\n"
                + "    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "<div id=\"block-menu-menu-main-right-footer\" class=\"block block-menu   odd\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <ul class=\"menu\"><li class=\"first leaf\"><a href=\"https://ateneo.edu/udpo/ADMU-Privacy-Policies\" target=\"_blank\">Privacy Policy</a></li>\n"
                + "<li class=\"leaf\"><a href=\"http://www.ateneo.edu/feedback\" target=\"_blank\">CONTACT US</a></li>\n"
                + "<li class=\"leaf\"><a href=\"http://www.ateneo.edu/ucpro\" target=\"_blank\">University Communication</a></li>\n"
                + "<li class=\"leaf\"><a href=\"http://www.ateneo.edu/careers\" target=\"_blank\">Careers</a></li>\n"
                + "<li class=\"last leaf\"><a href=\"http://www.ateneo.edu/news/emergency-information\" class=\"first\" target=\"_blank\">Emergency Information</a></li>\n"
                + "</ul>    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "<div id=\"block-block-10\" class=\"block block-block   even\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            <h2 class=\"title block-title\">Follow Us On:</h2>\n"
                + "        \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <!-- AddThis Follow BEGIN -->\n"
                + "\n"
                + "<div class=\"addthis_toolbox addthis_default_style\">\n"
                + "<ul>\n"
                + "	<li><a class=\"addthis_button_facebook_follow\" addthis:userid=\"ateneodemanila\" style=\"margin-top:2px;\"></a></li>\n"
                + "	<li><a class=\"addthis_button_twitter_follow\" addthis:userid=\"ateneodemanilau\" style=\"margin-top:2px;\"></a></li>\n"
                + "	<li><a class=\"addthis_button_youtube_follow\" addthis:userid=\"ateneodemanilau\" style=\"margin-top:2px;\"></a></li>\n"
                + "  <li><a class=\"addthis_button_instagram_follow\" addthis:userid=\"theateneo\" style=\"margin-top:2px;\"></a></li>\n"
                + "	<li><span class=\"st_sharethis\" ></span></li>\n"
                + "        <li><a class=\"email\" href=\"mailto:webmaster@admu.edu.ph\"><img src=\"/sites/all/modules/socialmedia/icons/levelten/glossy/16x16/email.png\" style=\"margin-top:2px; margin-left:4px;\"></a></li>\n"
                + "</ul>\n"
                + "</div>\n"
                + "\n"
                + "<script type=\"text/javascript\" src=\"http://s7.addthis.com/js/300/addthis_widget.js#pubid=xa-5075146655e5c36f\"></script>\n"
                + "<!-- AddThis Follow END -->\n"
                + "<script type=\"text/javascript\" src=\"http://w.sharethis.com/button/buttons.js\"></script>\n"
                + "<script type=\"text/javascript\">\n"
                + "        stLight.options({\n"
                + "                publisher:'8525bf31-4657-4209-9439-c7d6888d68db'\n"
                + "        });\n"
                + "</script>    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "<div id=\"block-block-4\" class=\"block block-block  last odd\">\n"
                + "  <div class=\"gutter inner clearfix\">\n"
                + "            \n"
                + "    <div class=\"content clearfix\">\n"
                + "      <p>Ateneo de Manila University Loyola Heights Campus | Katipunan Avenue, Loyola Heights, Quezon City 1108, Philippines | Copyright  2006-2012 | Ateneo de Manila University. All rights reserved.</p>\n"
                + "    </div>\n"
                + "  </div><!-- /block-inner -->\n"
                + "</div><!-- /block -->\n"
                + "    </div><!-- /footer-inner -->\n"
                + "  </div><!-- /footer -->\n"
                + "</div><!-- /footer-wrapper -->\n"
                + "    </div><!-- /page-inner -->\n"
                + "  </div><!-- /page -->  <script type=\"text/javascript\">\n"
                + "<!--//--><![CDATA[//><!--\n"
                + "Cufon.now();\n"
                + "//--><!]]>\n"
                + "</script>\n"
                + "</body>\n"
                + "</html>";
    }
}
